# docker-compose.yml

version: '3.8'

services:
  # Node.js Application Service
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb+srv://admin:admin123@test-devices.ugeunq6.mongodb.net
      - JWT_SECRET=f002fa035d86395c
      - JWT_EXPIRES_IN=1d
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
